name: 🚀 Docker CI/CD → Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your code
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      # 2. Ensure Docker Buildx is available (optional for advanced builds)
      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Install Railway CLI
      - name: 🔧 Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      # 4. Deploy using Railway (your Dockerfile is picked up automatically)
      - name: 🚀 Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service web
